language: node_js

git:
  # Minimize git history, but ensure to not break things:
  # - Merging multiple PR's around same time may introduce a case where it's not
  #   the last merge commit that is to be tested
  # - Aside of merge commit we need a previous commit to be able to detect a version switch
  depth: 10

cache:
  # Not relying on 'npm' shortcut, as per Travis docs it's the only 'node_modules' that it'll cache
  directories:
    - $HOME/.npm
    - node_modules

branches:
  only:
    - master # Do not build PR branches
    - /^v\d+\.\d+\.\d+$/ # Ensure to build release tags

stages:
  - name: Test
  - name: Deploy
    if: tag =~ ^v\d+\.\d+\.\d+$

env:
  global:
    - FORCE_COLOR=1 # Ensure colored output (color support is not detected in some cases)

# Ensure to install dependencies at their latest versions
install:
  # Note: with `npm update` there seems no way to update all project dependency groups in one run
  - npm update --no-save # Updates just dependencies
  # Note: npm documents --dev option for dev dependencies update, but it's only --save-dev that works
  - npm update --save-dev --no-save # Updates just devDependencies

before_script:
  # Fail build right after first script fails. Travis doesn't ensure that: https://github.com/travis-ci/travis-ci/issues/1066
  # More info on below line: https://www.davidpashley.com/articles/writing-robust-shell-scripts/#idm5413512
  - set -e

# Ensure to fail build if deploy fails, Travis doesn't ensure that: https://github.com/travis-ci/travis-ci/issues/921
before_deploy:
  # Remove eventual old npm logs
  - rm -rf ~/.npm/_logs
after_deploy:
  - |
    # npm creates log only on failure
    if [ -d ~/.npm/_logs ]; then
      # Undocumented way to force Travis build to fail
      travis_terminate 1
    fi

jobs:
  include:
    # In most cases it's best to configure one job per platform & Node.js version combination
    # (job boot & setup takes ca 1 minute, one task run lasts ca few seconds)

    # PR's from branches
    # Ensure commit messages follow CC, and confirm on changelog in case of release PR's
    - name: 'Prettier check updated, Lint updated, Commitlint, Changelog confirm (on release) - Node.js v12'
      if: type = pull_request AND fork = false
      node_js: 12
      script:
        - npm run prettier-check:updated
        - npm run lint:updated
        - npm run commitlint-ci-pull-request
        # If release PR, confirm we have a changelog
        - |
          tagName=`git diff master package.json | grep '"version": "' | tail -n 1 | grep -oE "[0-9]+\.[0-9]+\.[0-9]+"` || :
          if [ -n "$tagName" ];
          then
            npx dump-release-notes-from-cc-changelog $tagName
          fi

    # PR's from forks
    # Do not validate commit messages,
    # (if user didn't ensure CC, PR should be squash merged with a valid CC commit message)
    - name: 'Prettier check updated, Lint updated - Node.js v12'
      if: type = pull_request AND fork = true
      node_js: 12
      script:
        - npm run prettier-check:updated
        - npm run lint:updated

    # master branch
    - name: 'Lint, Tag on version bump - Node.js v12'
      env:
        # GITHUB_TOKEN
        - secure: OjSOXUWhRPUy2lQ8BcnrVpO6fzqisFh2LzSln0fOSo8pDFmKhkNsLvPufHg4SuZg+ynpV19ZXPFGAiiBAS0C0i+NUxUcunmRI+gmdobbdnMf40yw7PanqBzL33IlicsE8U/0mqC+ha7lF5zQcNLTZXzMDarKQVklqbW/GrgLy6kFmohf9dDDGxHeKtIF5qk3djiFfatNf2Q+eyNI8/nxlCFqqy0fhFQJUL2kqJTYXn8CwhIMQP3Qn3SqGTJhrjFbn0VwmKdKn/QIcaEec9m6he9gzWWIXXsB3YkPO63hm0FThqnf23Z72xfF03BrAqIkRpN5SrcpqcNgZ1KVd2lEnXG6uBYCGpK2kG/qNEYuKI7edv+Ns6G7i/DuStL7l82jvnedyjYgFYjXMynEtK5j2WDHwPGje5bo62OlXcsqxD0Q8s0KE0UM4dyLXCTlVmTvjIl/r3fIlxrUGGpZWpV/PwvDdtFsRYnszj/uhlZ9OIoytCHFYtrms/8sKj8YupcDTx66sUoBO9IhHuXmkk0FotzGgVaCT+WK/3Pqfdx7WnfVNz7FKC418huBH4ifnq9Erah7BWiQcU6xpDvwSwsEWSbCVRPO/RNaC8IPM2/rVraubvXHhU4P+DUOvCKoHA2g8ZmJirIATsvPbZ7iknsOg3olYAKR5zyI6Iwu2bDHCH4=
      if: branch = master AND type = push
      node_js: 12
      script:
        - npm run lint
        # If package version was changed with last merged PR, push tag
        - |
          tagName=`git diff HEAD^ package.json | grep '"version": "' | tail -n 1 | grep -oE "[0-9]+\.[0-9]+\.[0-9]+"` || :
          if [ -n "$tagName" ];
          then
            git tag v$tagName
            git push -q https://$GITHUB_TOKEN@github.com/serverless-components/tencent-koa --tags
          fi

    # version tag
    - stage: Deploy
      env:
        # GITHUB_TOKEN
        - secure: OjSOXUWhRPUy2lQ8BcnrVpO6fzqisFh2LzSln0fOSo8pDFmKhkNsLvPufHg4SuZg+ynpV19ZXPFGAiiBAS0C0i+NUxUcunmRI+gmdobbdnMf40yw7PanqBzL33IlicsE8U/0mqC+ha7lF5zQcNLTZXzMDarKQVklqbW/GrgLy6kFmohf9dDDGxHeKtIF5qk3djiFfatNf2Q+eyNI8/nxlCFqqy0fhFQJUL2kqJTYXn8CwhIMQP3Qn3SqGTJhrjFbn0VwmKdKn/QIcaEec9m6he9gzWWIXXsB3YkPO63hm0FThqnf23Z72xfF03BrAqIkRpN5SrcpqcNgZ1KVd2lEnXG6uBYCGpK2kG/qNEYuKI7edv+Ns6G7i/DuStL7l82jvnedyjYgFYjXMynEtK5j2WDHwPGje5bo62OlXcsqxD0Q8s0KE0UM4dyLXCTlVmTvjIl/r3fIlxrUGGpZWpV/PwvDdtFsRYnszj/uhlZ9OIoytCHFYtrms/8sKj8YupcDTx66sUoBO9IhHuXmkk0FotzGgVaCT+WK/3Pqfdx7WnfVNz7FKC418huBH4ifnq9Erah7BWiQcU6xpDvwSwsEWSbCVRPO/RNaC8IPM2/rVraubvXHhU4P+DUOvCKoHA2g8ZmJirIATsvPbZ7iknsOg3olYAKR5zyI6Iwu2bDHCH4=
      node_js: 12
      script: skip
      deploy:
        edge: true # Workaorund Travis regression: https://travis-ci.community/t/missing-api-key-when-deploying-to-github-releases/5761
        provider: npm
        email: services@serverless.com
        on:
          tags: true
        api_key:
          secure: nGwhcVScdO3geg5iL6VVt0Xpb2vLgYX72VrCJkgxTqrIY3y98A6MOCf/T6e62/3+/+ruKRnzGz3LhcquvDnA34NTO5c6t0d2JD9yQzqkOR5qNMTtSKq9m2G+dKCW2Meh/8+3qtpTWVQ7hpvLGJVCbcpdcI4A/bSlnmWnuJZWC7+oLIKi7edwyw8cmqqWYiuSX00e1BVZh2MlBMtOR2XygeLTEtpX1Oy5q1pfzZwroOWeDXoa+SQPyh3gSo0R2y8EQIb7d85i4gJ0pcf1W3SExU/amamFFYJv6VCb/fRKwAfhQUsAgALjaP9vmqes19Cklw7Oo4pOUwx2/9NksvyPGoymG0FHvU1vvJXZhSmsENV+dsAmUu3FIuQ8hwSWkW02MD1AlOLCf3iZgpirteOhsrMyQt6to5bWi7iyPT9mGBVPKuoscEl+/mryLlOswoXpqmgTUpLdcSxkCUNgGvVVcYL+grzsOaeuohKJNQo3KV/Wdqk3cpRhfWmt8swOY62E21vF/q3OezGH7SIa69vdfIBxhc7UbHtMUToj9tC5P6Ch8YQVCg3ZI+1eitbs3nMF9GdKylzSeslES/UwUbodXCfBHCc+j3XswPEixNDOu78pJ43JeOWSTlMExeCtnnOKPn8O/kGchBn5QGgD9zna2Ji3VrhBTkmoA9otQRaz5fU=
      after_deploy: npx github-release-from-cc-changelog $TRAVIS_TAG
